server:  
  port: ${PORT:8762}
spring:  
  cloud:
    config:
      server:
        git:
          uri: https://github.com/israel-anaya/startup-framework-demo-config.git
          force-pull: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
logging:
  level:    
    root: INFO
    org.springframework.cloud.config: TRACE