server:  
  port: ${PORT:0}
  tomcat:
    threads:
      max: 5
spring:  
  cloud:
    config:
      server:
        git:
          uri: https://github.com/israel-anaya/startupframework-demo-config.git
          force-pull: true
eureka:
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
logging:
  level:    
    root: INFO
    org.springframework.cloud.config: TRACE