server:  
  port: ${PORT:0}
  tomcat:
    max-threads: 5
spring:  
  application:
    name: startup-starter-msa-config-server-${spring.profiles.active}
  autoconfigure:
    exclude:
    - org.springframework.boot.autoconfigure.security.SecurityAutoConfiguration
    - org.springframework.boot.autoconfigure.security.SecurityFilterAutoConfiguration
    - org.springframework.boot.autoconfigure.security.FallbackWebSecurityAutoConfiguration
    - org.springframework.boot.autoconfigure.security.oauth2.OAuth2AutoConfiguration
    - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
    - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration      
     

