server:  
  port: ${PORT:8761}
  tomcat:
    threads:
      max: 5
eureka:
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
logging:
  level:    
    root: INFO
    org.springframework.cloud.config: TRACE
    org.springframework.cloud.netflix.eureka: INFO
    com.netflix.eureka: INFO
    com.netflix.discovery: INFO