server:  
  port: ${PORT:8761}
eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
logging:
  level:    
    org.springframework.cloud.config: TRACE
    org.springframework.cloud.netflix.eureka: INFO
    com.netflix.eureka: INFO
    com.netflix.discovery: INFO