metadata:
  namespace: startup
spec:
  replicas: 1
  template:
    spec:
      containers:
      - imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: ${project.artifactId}           
        resources:
          limits:
            memory: 256Mi
          requests:
            memory: 256Mi
        ports:
        - name: http-service
          containerPort: 8080          
          protocol: TCP
        livenessProbe:
          httpGet:
            port: http-service
            path: /actuator/health
          initialDelaySeconds: 300
          periodSeconds: 30
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            port: http-service
            path: /actuator/health
          initialDelaySeconds: 300
          periodSeconds: 30
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        volumeMounts:
        - mountPath: "/var/log/sb-app/"
          name: container-log
      volumes:
      - name: container-log
        emptyDir: {}
